# Generated by Django 4.2.7 on 2025-10-24 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('department', models.CharField(choices=[('MATH', 'Mathematics'), ('SCIENCE', 'Science'), ('ENGLISH', 'English'), ('HISTORY', 'History'), ('GEOGRAPHY', 'Geography'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('BIOLOGY', 'Biology'), ('COMPUTER', 'Computer Science'), ('ART', 'Art'), ('MUSIC', 'Music'), ('PE', 'Physical Education'), ('OTHER', 'Other')], max_length=20)),
                ('specialization', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('office_room', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
                'ordering': ['-join_date'],
                'indexes': [models.Index(fields=['teacher_id'], name='teachers_teacher_456fe5_idx'), models.Index(fields=['department'], name='teachers_departm_174d34_idx')],
            },
        ),
    ]
