# Generated by Django 4.2.7 on 2025-10-24 11:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2')], max_length=1)),
                ('academic_year', models.CharField(help_text='e.g., 2023-2024', max_length=9)),
                ('schedule', models.CharField(help_text='e.g., Mon/Wed/Fri 10:00-11:30', max_length=200)),
                ('room', models.CharField(max_length=50)),
                ('max_students', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('DROPPED', 'Dropped'), ('COMPLETED', 'Completed')], default='ENROLLED', max_length=20)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('F', 'F'), ('I', 'Incomplete'), ('W', 'Withdrawn')], max_length=2, null=True)),
                ('grade_points', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollments',
                'ordering': ['-enrollment_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='enrollments_student_929bef_idx'), models.Index(fields=['course', 'status'], name='enrollments_course__931283_idx'), models.Index(fields=['enrollment_date'], name='enrollments_enrollm_4c2d2b_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_code'], name='courses_course__5da9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['academic_year', 'semester'], name='courses_academi_e95e89_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_status_67f368_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_code', 'academic_year', 'semester')},
        ),
    ]
